### ISSUE TITLE
[REQUEST] Skill checks config file

### ISSUE THREAD

**Issue by liana-p** [liana-p/narrat-engine#61]
**Is your feature request related to a problem? Please describe.**
Skill checks have a lot of complicated options already, and we've been avoiding adding more because it would make scripts and the roll command too complex. For example right now the last option of the roll command is a string of either `hideAfterRoll` or `repeatable`, but this won't scale very well.

We should add a way to configure specific skill checks in a yaml config file, like we do for other things, to allow for more complex options.

**Describe the solution you'd like**
Skill checks should still work the same way as before where they can be done directly using a `roll`, but setting specific complex ones up in a config file should be an alternative. For example, in a yaml file:

```yaml
skillChecks:
  mySkillCheckId:
    skill: agility
    difficulty: 10
    hideAfterRoll: false
    repeatable: true
  myOtherSkillCheckId:
    //... and so on
```

Using this config, the places in the code that run skill checks should find out the options for the roll if they exist. Then, usage in a script could simply be:

`roll mySkillCheckId`

It's important that we don't force the user to put every skill check in the config file though as it would be tedious. this config file should be optional for complex skill checks that people want to keep in a config file, or for future advanced roll options that couldn't fit in a one-line command.
